### PR TITLE
Implement regex whitelist feature for "Haha Creatures do Brrrr"

### LINKED ISSUE #7283: "Haha Creatures do Brrrr" becomes "Haha Creatures do Rakdos"
Reported on Discord by bakert#2193

### PR DESCRIPTION
**Pull request by kzcheng**
Fix #7283

### CODE REVIEW

**Comment by kzcheng** [comment]
Please don't merge this yet. I'm still working on it.

I'm trying to clean everything up first. The issue is fixed but still needs clean up.

Also might need more testing, unit testing is done, but haven't tried on the website yet.

**Comment by bakert** [comment]
I think there's some merit to this approach but I think we are better off disallowing *all* matches of [WUBRG] that have a repeat?

Under the current system 'UUU' becomes 'Blue' and 'UUGGGGGGGG' becomes 'Simic'. I think it's better to reject those as not  color matches?  (Although we do have a deck called 'BBB' that features in the tests.)

One way to achieve the blanket repetition disallow instead of having a whitelist is:

```
diff --git a/decksite/deck_name.py b/decksite/deck_name.py
index f1c43233..bdeb3992 100644
--- a/decksite/deck_name.py
+++ b/decksite/deck_name.py
@@ -149,7 +149,12 @@ def normalize_colors(name: str, colors: List[str]) -> str:
         regex = regex_pattern(pattern)
         found = re.search(regex, name, flags=re.IGNORECASE)
         if found:
-            unique_color_words[found.group().strip()] = True
+            color_word = found.group().strip()
+            if re.search('^[WUBRG]+$', color_word, flags=re.IGNORECASE):
+                unique = len(set(color_word)) == len(color_word)
+                if not unique:
+                    continue
+            unique_color_words[color_word] = True
     if len(unique_color_words) == 0:
         return name
     color_words = list(unique_color_words.keys())
@@ -176,7 +181,7 @@ def canonicalize_colors(colors: List[str]) -> Set[str]:
     return set(mana.order(canonical_colors))
 
 def regex_pattern(pattern: str) -> str:
-    return '(^| )(mono[ -]?)?{pattern}( |$)'.format(pattern=pattern)
+    return '(?:^| )(?:mono[ -]?)?({pattern})(?: |$)'.format(pattern=pattern)
 
 def standardize_color_string(s: str) -> str:
     colors = re.sub('mono|/|-', '', s, re.IGNORECASE).strip().lower()
diff --git a/decksite/deck_name_test.py b/decksite/deck_name_test.py
index 4b32bfb9..23bd5bd7 100644
--- a/decksite/deck_name_test.py
+++ b/decksite/deck_name_test.py
@@ -81,7 +81,7 @@
     ('PD-GB', 'Golgari the Rock', ['G', 'B'], 'The Rock'),
     ('PD 11 WW', 'White Weenie', ['W'], None),
     ('Bad Esper 2.0', 'Bad Esper 2.0', ['W', 'U', 'B'], 'Esper Control'),
-    ('BBB', 'Mono Black', ['B'], 'Zombies'),
+    ('BBB', 'BBB', ['B'], 'Zombies'),
     ('Manaless Dredge', 'Manaless Dredge', ['B'], 'Graveyard Value'),
     ('Deep Anal', 'Deep', ['U'], 'Control'),
     ('Supremacia Ariana', 'Mono White', ['W'], None),
@@ -98,7 +98,8 @@
     ('Happy B DAY Adriana', 'Happy B Day Adriana', ['W', 'R'], 'AggroSlide'),
     ('braids b', 'Braids Black', ['B'], 'Midrange'),
     ('[Penny Dreadful] UR Cycling', 'Izzet Cycling', ['U', 'R'], 'Midrange'),
-    ('Penny-Zombies', 'Zombies', ['B'], 'Zombies')
+    ('Penny-Zombies', 'Zombies', ['B'], 'Zombies'),
+    ('Something Goes Brrrr', 'Something Goes Brrrr', ['B', 'R'], 'Aggro')
 ]
 
 @pytest.mark.parametrize('original_name,expected,colors,archetype_name', TESTDATA)
```

I'm not in love with it but it's a bit nicer than a whitelist. I think?

**Comment by silasary** [comment]
Considering we've also seen issues with 'uwu' getting normalized, yeah, we probably want to just not act on words with duplicate letters.

**Comment by kzcheng** [comment]
@bakert 

Yeah Tom, we should probably ignore all patterns with duplications.

Fortunately, by adding a regex pattern to the `WHITELIST_PATTERNS`, we can ignore anything we want.

@silasary 

I'll add in `uwu` now

**Comment by kzcheng** [comment]
Did a few tests on the Decksite, everything seems to be working properly.

You can merge this pull request now.

**Comment by bakert** [comment]
Closed in favor of #7686

**Pull request closed without merging**
