### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by silasary**

### CODE REVIEW

**Comment by silasary** [comment]
Um?

**Comment by bakert** [comment]
I think one of the feeds changed. Prices are not updating because of this same thing.

**Comment by bakert** [comment]
actually `2015-10-02T00:00:00.000` is a pure bs date so one of the feeds changed AND it's buggy.

**Comment by silasary** [comment]
Oh.  It's almost certainly https://github.com/glacials/whatsinstandard/commit/606e2fbbac7275be984aabb273e0556f643dc60e

**Comment by bakert** [comment]
ah, good find. "nonbreaking change" ho ho ho. these people have got too used to php's strtotime :D

**Pull request merged**
