### PR TITLE
Cards records and unsquished images.

### PR DESCRIPTION
**Pull request by bakert**

### CODE REVIEW

**Comment by bakert** [comment]
E   apsw.ExtensionLoadingError: ExtensionLoadingError: ./spellfix.so: undefined symbol: sqlite3_spellfix_init

Hm.

**Comment by bakert** [comment]
@silasary `make test` passes on local and prod. How can I repro on ci.katelyngigante.com?

**Comment by silasary** [comment]
It compiled a bad `spellfix.so`.  I fixed it on branch, but forgot to fix the pr-merge build.

**Comment by silasary** [comment]
Manually fixing it now, but it's making me rethink my decision to not rebuild the whole thing every build

**Comment by silasary** [comment]
That said... How did it manage to compile a bad build, and why did it happen in two separate builds, but never again before or after.

**Pull request merged**
