### PR TITLE
Revert "pytest doesn't need the find xargs.  It's fully capable of finding tests on its own."

### PR DESCRIPTION
**Pull request by bakert**
This reverts commit 21ea24a0bf4b764b966d9af526ead158f1d5b48e.

This stops the TEST={search_string} commandline param working so reverting.

### CODE REVIEW

**Comment by bakert** [comment]
bors r+

I'm gonna keep doing this

**Comment by silasary** [comment]
Synchronised its state over at https://app.bors.tech/repositories/1281, hopefully it works this time.

bors r+

**Comment by bakert** [comment]
curse ye bors

**Comment by silasary** [comment]
It's currently running 😛

**Comment by bakert** [comment]
it did say "not awaiting review" to me though. confusink.

**Comment by silasary** [comment]
Yeah, it's a very ambiguous error message.  It essentially means "I'm not in the start where you should be asking me to make a merge commit"

Sometimes it's because the PR is closed, sometimes because it's running, sometimes it's because a github webhook failed.

**Comment by silasary** [comment]
I should probably open an issue on the bors-ng repo about it.

**Pull request merged**
