### PR TITLE
Tooltips: Refactor to ES6 and add support for touch and tab input.

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Follow-up to our Discord chat.

@bakert, can you take a look? I'm not sure how you manage regressions in your UI.

### CODE REVIEW

**Comment by bakert** [comment]
Unfortunately the tooltips no longer function after this change:

```Uncaught TypeError: Cannot read property '0' of undefined
    at Object.pointerX (tooltips.js?v=4d1aec5155b01e5f2863472e2d89da4e4c27b1fa:115)
    at HTMLDocument.onpointermove (tooltips.js?v=4d1aec5155b01e5f2863472e2d89da4e4c27b1fa:262)```

**Review by bakert — CHANGES_REQUESTED** [review]
Sorry it took me so long to take a look. Looks like there's something awry.

**Comment by CodyJasonBennett** [comment]
How are we using this?

The only thing I could find is that we're listening to the wrong events when toggling for touch devices in [`shared_web/static/js/pd.js`](https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/blob/master/shared_web/static/js/pd.js#L155). This should be the pointer event.

**Comment by bakert** [comment]
Steps to repro:

- Checkout refactor/tooltips branch (or `gh pr 8354`)
- Spin up pennydreadfulmagic.com on local with `python3 run.py decksite`
- Visit http://localhost:5000/cards/ and mouseover the cards

Expected:

- Card images show up like they do on https://pennydreadfulmagic.com/cards/

Actual:

- No card images and console says: 

```
Uncaught TypeError: Cannot read property '0' of undefined
    at Object.pointerX (tooltips.js?v=afb03de5a844c31929cea331289d074ec90c4057:115)
    at HTMLDocument.onpointermove (tooltips.js?v=afb03de5a844c31929cea331289d074ec90c4057:262)
```

**Comment by CodyJasonBennett** [comment]
I see. I'm dangerously checking whether pointer events have touches.

```diff
-const input = (event.touches[0] || event)
+const [input] = (event.touches || [event])
```

**Comment by bakert** [comment]
That does make the errors go away but I don't see any card images :)

**Comment by CodyJasonBennett** [comment]
Moved to #8422.

**Pull request closed without merging**
