### PR TITLE
merge from master

### PR DESCRIPTION
**Pull request by adambiltcliffe**

### CODE REVIEW

**Comment by silasary** [comment]
What's going on here?

**Comment by adambiltcliffe** [comment]
I don't know, but everything worked fine.

**Comment by bakert** [comment]
Look at make push in the Makefile for a
sensible set of things to do on your branch before opening a PR.

**Comment by adambiltcliffe** [comment]
Actually the issue here is I don't think I should have made a PR at all.

**Comment by silasary** [comment]
Nope.

**Comment by bakert** [comment]
Oh. Ok! :)

**Pull request merged**
