### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by silasary**

### CODE REVIEW

**Comment by silasary** [comment]
Breaking changes upstream.

**Comment by bakert** [comment]
There is a Markdown 3.0.1 now so I wonder if this can go through.

**Comment by bakert** [comment]
Reverted the _ change to please codacy and see if this goes through now …

**Comment by bakert** [comment]
ok I get it now. Codacy doesn't want us to have an unused param that doesn't start with '_' and pylint doesn't want us to override a param without using the same name as the param it overrides. I would say pylint is "wrong" here although it's a marginal call between two broadly sensible ideas. I'll just exclude it from pylint inline.

**Pull request merged**
