### PR TITLE
Price grabber was doing bad things.

### PR DESCRIPTION
**Pull request by silasary**
I have a feeling that a SQL query that inserts 16,601 rows in a single INSERT might be bad for mysql.

bors r+

### CODE REVIEW

**Comment by bakert** [comment]
Did you time it? My guess is that this is going to be slower and that it's the (single) caching query that's still the slowest thing. But I live to be wrong :D

**Comment by silasary** [comment]
Yeah, this was significantly faster for me on local.

The mysql buffer was bottlenecking on me.

**Comment by silasary** [comment]
The cache query all happens within mysql, and seems to be pretty good at what it does.

**Pull request merged**
